name: fastdealer
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  signature: ^5.5.0
  share_plus: ^6.0.0  # share_plus 패키지로 변경
  http: ^1.2.2
  path_provider: ^2.0.11
  url_launcher: ^6.0.9
  open_file_plus: ^3.4.1+1
  permission_handler: ^10.0.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/contract.xlsx
    - assets/report.xlsx
    - assets/contract_image.png
    - assets/
